# Generated by Django 3.1 on 2020-09-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_auto_20200916_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.AddField(
            model_name='producto',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommapp.cupon'),
        ),
    ]
